const vessels = [
    {
        // Group 1
        vessel0: "/assets/models/vessels/1/0.glb",
        vessel1: "/assets/models/vessels/1/1.glb",
        vessel2: "/assets/models/vessels/1/2.glb",
        vessel3: "/assets/models/vessels/1/3.glb",
        vessel4: "/assets/models/vessels/1/4.glb",
        vessel5: "/assets/models/vessels/1/5.glb",
        vessel6: "/assets/models/vessels/1/6.glb",
        vessel7: "/assets/models/vessels/1/7.glb",
        vessel8: "/assets/models/vessels/1/8.glb",
        vessel9: "/assets/models/vessels/1/9.glb",
        vessel10: "/assets/models/vessels/1/10.glb",
        vessel11: "/assets/models/vessels/1/11.glb",
        vessel12: "/assets/models/vessels/1/12.glb",
        vessel13: "/assets/models/vessels/1/13.glb",
        vessel14: "/assets/models/vessels/1/14.glb",

        // Group 2
        vessel15: "/assets/models/vessels/2/0.glb",
        vessel16: "/assets/models/vessels/2/1.glb",
        vessel17: "/assets/models/vessels/2/2.glb",
        vessel18: "/assets/models/vessels/2/3.glb",
        vessel19: "/assets/models/vessels/2/4.glb",
        vessel20: "/assets/models/vessels/2/5.glb",
        vessel21: "/assets/models/vessels/2/6.glb",
        vessel22: "/assets/models/vessels/2/7.glb",
        vessel23: "/assets/models/vessels/2/8.glb",
        vessel24: "/assets/models/vessels/2/9.glb",
        vessel25: "/assets/models/vessels/2/10.glb",
        vessel26: "/assets/models/vessels/2/11.glb",
        vessel27: "/assets/models/vessels/2/12.glb",
        vessel28: "/assets/models/vessels/2/13.glb",
        vessel29: "/assets/models/vessels/2/14.glb",        
        vessel30: "/assets/models/vessels/2/15.glb",
        vessel31: "/assets/models/vessels/2/16.glb",

        // Group 3
        vessel32: "/assets/models/vessels/3/0.glb",
        vessel33: "/assets/models/vessels/3/1.glb",
        vessel34: "/assets/models/vessels/3/2.glb",
        vessel35: "/assets/models/vessels/3/3.glb",
        vessel36: "/assets/models/vessels/3/4.glb",
        vessel37: "/assets/models/vessels/3/5.glb",
        vessel38: "/assets/models/vessels/3/6.glb",
        vessel39: "/assets/models/vessels/3/7.glb",
        vessel40: "/assets/models/vessels/3/8.glb",
        vessel41: "/assets/models/vessels/3/9.glb",
        vessel42: "/assets/models/vessels/3/10.glb",
        vessel43: "/assets/models/vessels/3/11.glb",
        vessel44: "/assets/models/vessels/3/12.glb",
        vessel45: "/assets/models/vessels/3/13.glb",
        vessel46: "/assets/models/vessels/3/14.glb",
        vessel47: "/assets/models/vessels/3/15.glb",
        vessel48: "/assets/models/vessels/3/16.glb",
        vessel49: "/assets/models/vessels/3/17.glb",
        vessel50: "/assets/models/vessels/3/18.glb",

        // Group 4
        vessel51: "/assets/models/vessels/4/0.glb",
        vessel52: "/assets/models/vessels/4/1.glb",
        vessel53: "/assets/models/vessels/4/2.glb",
        vessel54: "/assets/models/vessels/4/3.glb",
        vessel55: "/assets/models/vessels/4/4.glb",
        vessel56: "/assets/models/vessels/4/5.glb",
        vessel57: "/assets/models/vessels/4/6.glb",
        vessel58: "/assets/models/vessels/4/7.glb",
        vessel59: "/assets/models/vessels/4/8.glb",
        vessel60: "/assets/models/vessels/4/9.glb",
        vessel61: "/assets/models/vessels/4/10.glb",
        vessel62: "/assets/models/vessels/4/11.glb",
        vessel63: "/assets/models/vessels/4/12.glb",
        vessel64: "/assets/models/vessels/4/13.glb",
        vessel65: "/assets/models/vessels/4/14.glb",        
        vessel66: "/assets/models/vessels/4/15.glb",

        // Group 5
        vessel67: "/assets/models/vessels/5/0.glb",
        vessel68: "/assets/models/vessels/5/1.glb",
        vessel69: "/assets/models/vessels/5/2.glb",
        vessel70: "/assets/models/vessels/5/3.glb",
        vessel71: "/assets/models/vessels/5/4.glb",
        vessel72: "/assets/models/vessels/5/5.glb",
        vessel73: "/assets/models/vessels/5/6.glb",
        vessel74: "/assets/models/vessels/5/7.glb",
        vessel75: "/assets/models/vessels/5/8.glb",
        vessel76: "/assets/models/vessels/5/9.glb",
        vessel77: "/assets/models/vessels/5/10.glb",
        vessel78: "/assets/models/vessels/5/11.glb",
        vessel79: "/assets/models/vessels/5/12.glb",
        vessel80: "/assets/models/vessels/5/13.glb",
    }
]